# Generated by Django 4.2.2 on 2023-07-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
